name: Hello, world!
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Hello, world!
        run: echo "Hello, world!"
